# Stage 1: Build the application
FROM node:24.13

WORKDIR /app

# Copy package.json and package-lock.json for dependency installation
# We need the root package.json and package-lock.lock for nx commands
COPY ../../package*.json ./

CMD npm install --prefer-offline && \
    npx nx run azure-storage:serve:development
