# Stage 1: Build the application
FROM node:24-alpine

WORKDIR /app

COPY ../../package*.json ./
RUN npm install

RUN npx nx sync

CMD npx wait-port rabbit:5672 && \
    npx nx run history:serve:development

