apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-fixture-rest-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-fixture-rest-api
  template:
    metadata:
      labels:
        app: db-fixture-rest-api
    spec:
      containers:
        - name: db-fixture-rest-api
          image: db-fixture-rest-api:latest
          imagePullPolicy: Never
          livenessProbe:
            httpGet:
              path: /alive
              port: 80
          readinessProbe:
            httpGet:
              path: /ready
              port: 80
            initialDelaySeconds: 5
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: db-fixture-rest-api-config
                  key: port
            - name: FIXTURES_DIR
              valueFrom:
                configMapKeyRef:
                  name: db-fixture-rest-api-config
                  key: fixturesDir
            - name: DB_FIXTURES_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-fixture-rest-api-config
                  key: dbFixturesDbHost
